//Invoking generateRandomColors and generate Array of Colors
var numSquares = 6;

var colors = generateRandomColors(numSquares)

//Message variable
var messageDisplay = document.getElementById("message");

//picked Color
var pickedColor = pickColor();

//To display in h1
document.querySelector("#name").textContent = pickedColor;

//each div
var squares = document.getElementsByClassName("square");

//Selecting h1
var title = document.getElementById("title");

//Selecting the Button
var resetButton = document.querySelector("#reset");

//Selecting the Strenght button (easy vs hard)
var easy = document.getElementById("easy");
var hard = document.getElementById("hard");

var numberSqure;


//Buttons=============================//=============== 
//And EASY vs HARD button
//EASY
easy.addEventListener("click", function(){
	easy.classList.add("selected");
	hard.classList.remove("selected");
	numSquares = 3;


	//invoking generateRandomColors() function
	colors = generateRandomColors(numSquares);
	pickedColor = pickColor();
	for(var i = 0; i < squares.length; i++){
		if(colors[i]){
			squares[i].style.background = colors[i];
		} else {
			squares[i].style.display = "none";
		};
	};

});

//HARD button 

hard.addEventListener("click", function(){
	hard.classList.add("selected");
	easy.classList.remove("selected");
	numSquares = 6;




	//invoking generateRandomColors() function
	colors = generateRandomColors(numSquares);
	pickedColor = pickColor();
	for(var i = 0; i < squares.length; i++){
		squares[i].style.background = colors[i];
		squares[i].style.display = "block";
	};
});

//==========================//==================




//RESET============================================

//Adding EventListeners to the RESETING button
resetButton.addEventListener("click", function(){
	//Generates new colors
	colors = generateRandomColors(numSquares);

	//Selects a new Color by invoking pickColor function...
	//depending on the length of the array generated by generateRandomeColors
	pickedColor = pickColor();

	//Changes the content of the title displayed in h1
	document.querySelector("#name").textContent = pickedColor;

	//Resets the background of the title
	title.style.background = "steelblue";

	//Displays the new colors in each square
	for (var i = 0; i < squares.length; i++){
		squares[i].style.background = colors[i];
		};

	//To reset the text on the Reset Button
	this.textContent = "NEW COLORS";


	//Resetting the message back to blank
	messageDisplay.textContent = "";

});

//====================//========================



//for loop assigning the above colors to html divs. 
for (var i = 0; i < squares.length; i++){
	squares[i].style.background = colors[i];
	squares[i].addEventListener("click", function(){
	var clickedColor = this.style.background;
	if(clickedColor === pickedColor){
		
		messageDisplay.textContent = "Correct!";
		changeColors(pickedColor);
		title.style.background = "steelblue";
		resetButton.textContent = "PLAY AGAIN?"
		

	} else { 
		this.style.background = "#232323";
		messageDisplay.textContent = "Try Again";
		
	}
	});
};





//FUNCTIONS============================================

//Function that intakes Array of colors and loops through the squers 
//And, changes the background of all the squares. Implemented is gussed correct!

function changeColors(col){
	for (var i = 0; i < squares.length; i++){
		squares[i].style.background = col;

	};
};


//Function to pick colors from the aray
//Returns a random number depending on the length of the array.
function pickColor(){
	var random = Math.floor(Math.random() * colors.length);
	return colors[random];
}



//Function that returns random color (three numbers)
function randomColor(){
	var r = Math.floor((Math.random() * 256));
	var g = Math.floor((Math.random() * 256));
	var b = Math.floor((Math.random() * 256));
	return "rgb("+r+", "+g+", "+b+")"	
};



//Function Array of random colors by invoking randomColor function. 
function generateRandomColors(numberSqure){
	var arrColor = []
	for(var i = 0; i < numberSqure; i++){
		arrColor.push(randomColor());
	};
	return arrColor;	
};



//============================================

